"""Add UNDER_REVIEW to StartupStatus enum manually

Revision ID: 0bab0d0ee0a6
Revises: b464f8e52f6b
Create Date: 2025-11-04 03:04:10.358025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bab0d0ee0a6'
down_revision = 'b464f8e52f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    new_options = ['ACTIVE', 'UNDER_REVIEW', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED']
    old_options = ['ACTIVE', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED']

    conn = op.get_bind()
    if conn.dialect.name == 'sqlite':
        # Create a temporary table with the new schema
        op.execute(f"""
            CREATE TABLE startups_new (
                id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                submission_id INTEGER,
                name VARCHAR(200) NOT NULL,
                slug VARCHAR(200),
                current_stage_key VARCHAR(50),
                overall_progress FLOAT,
                status VARCHAR(50), -- Use VARCHAR for SQLite, as ENUM is not directly supported
                created_at DATETIME,
                updated_at DATETIME,
                PRIMARY KEY (id),
                UNIQUE (submission_id),
                UNIQUE (user_id),
                UNIQUE (slug),
                FOREIGN KEY(submission_id) REFERENCES submissions (id),
                FOREIGN KEY(user_id) REFERENCES users (id)
            )
        """)
        # Copy data from old table to new table
        op.execute("""
            INSERT INTO startups_new (id, user_id, submission_id, name, slug, current_stage_key, overall_progress, status, created_at, updated_at)
            SELECT id, user_id, submission_id, name, slug, current_stage_key, overall_progress, status, created_at, updated_at
            FROM startups
        """)
        # Drop the old table
        op.drop_table('startups')
        # Rename the new table to the old table's name
        op.rename_table('startups_new', 'startups')
    else:
        # For other databases (e.g., PostgreSQL) that support direct ALTER TYPE
        with op.batch_alter_table('startups', schema=None) as batch_op:
            batch_op.alter_column(
                'status',
                existing_type=sa.Enum(*old_options, name='startupstatus'),
                type_=sa.Enum(*new_options, name='startupstatus'),
                existing_nullable=True
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    old_options = ['ACTIVE', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED']
    new_options = ['ACTIVE', 'UNDER_REVIEW', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED']

    conn = op.get_bind()
    if conn.dialect.name == 'sqlite':
        # Create a temporary table with the old schema
        op.execute(f"""
            CREATE TABLE startups_old (
                id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                submission_id INTEGER,
                name VARCHAR(200) NOT NULL,
                slug VARCHAR(200),
                current_stage_key VARCHAR(50),
                overall_progress FLOAT,
                status VARCHAR(50), -- Use VARCHAR for SQLite
                created_at DATETIME,
                updated_at DATETIME,
                PRIMARY KEY (id),
                UNIQUE (submission_id),
                UNIQUE (user_id),
                UNIQUE (slug),
                FOREIGN KEY(submission_id) REFERENCES submissions (id),
                FOREIGN KEY(user_id) REFERENCES users (id)
            )
        """)
        # Copy data from current table to old table, handling 'UNDER_REVIEW'
        op.execute("""
            INSERT INTO startups_old (id, user_id, submission_id, name, slug, current_stage_key, overall_progress, status, created_at, updated_at)
            SELECT id, user_id, submission_id, name, slug, current_stage_key, overall_progress,
                   CASE WHEN status = 'UNDER_REVIEW' THEN 'ACTIVE' ELSE status END, -- Convert 'UNDER_REVIEW' to 'ACTIVE' on downgrade
                   created_at, updated_at
            FROM startups
        """)
        # Drop the current table
        op.drop_table('startups')
        # Rename the old table to the current table's name
        op.rename_table('startups_old', 'startups')
    else:
        # For other databases (e.g., PostgreSQL) that support direct ALTER TYPE
        with op.batch_alter_table('startups', schema=None) as batch_op:
            batch_op.alter_column(
                'status',
                existing_type=sa.Enum(*new_options, name='startupstatus'),
                type_=sa.Enum(*old_options, name='startupstatus'),
                existing_nullable=True
            )
    # ### end Alembic commands ###
