"""Add unique constraint to submission user_id

Revision ID: 23a1da1f3a40
Revises: a05f88dc473c
Create Date: 2025-10-29 18:58:30.995367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a1da1f3a40'
down_revision = 'a05f88dc473c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_submissions_user_id', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_submissions_user_id', type_='unique')
    # ### end Alembic commands ###
