"""saved submission data correctly

Revision ID: 24750971c7d7
Revises: d9a3ccf0752e
Create Date: 2025-11-02 16:29:13.925077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24750971c7d7'
down_revision = 'd9a3ccf0752e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('market_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('funding_stage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('technical_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resources_needed', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('users_customers', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('key_achievements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('future_goals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_incubator', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('why_incubator')
        batch_op.drop_column('future_goals')
        batch_op.drop_column('key_achievements')
        batch_op.drop_column('revenue')
        batch_op.drop_column('users_customers')
        batch_op.drop_column('resources_needed')
        batch_op.drop_column('technical_skills')
        batch_op.drop_column('funding_stage')
        batch_op.drop_column('industry')
        batch_op.drop_column('market_size')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
