"""Initial migration

Revision ID: 2dc7171bcb98
Revises: 
Create Date: 2025-10-27 16:24:53.374541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc7171bcb98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startups_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_startups_submission_id'), ['submission_id'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('mvp_status', sa.String(length=50), nullable=True),
    sa.Column('mvp_progress_percentage', sa.Integer(), nullable=True),
    sa.Column('mvp_phases', sa.Text(), nullable=True),
    sa.Column('mvp_milestones', sa.Text(), nullable=True),
    sa.Column('gtm_status', sa.String(length=50), nullable=True),
    sa.Column('gtm_progress_percentage', sa.Integer(), nullable=True),
    sa.Column('gtm_phases', sa.Text(), nullable=True),
    sa.Column('gtm_milestones', sa.Text(), nullable=True),
    sa.Column('gtm_metrics', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('submission_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('stage_data', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_stages')
    op.drop_table('progress')
    op.drop_table('documents')
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startups_submission_id'))
        batch_op.drop_index(batch_op.f('ix_startups_email'))

    op.drop_table('startups')
    # ### end Alembic commands ###
