"""Refactor RoundInvestor PK to ID

Revision ID: 427589b4da73
Revises: aa96b1c2faa9
Create Date: 2026-01-20 04:09:11.384981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427589b4da73'
down_revision = 'aa96b1c2faa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    
    # 0. Cleanup from previous failed runs
    op.execute("DROP TABLE IF EXISTS round_investors_old")
    
    # 1. Rename existing table
    op.rename_table('round_investors', 'round_investors_old')
    
    # 2. Create new table with new schema (ID as PK)
    op.create_table('round_investors',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('round_id', sa.Integer(), sa.ForeignKey('funding_rounds.round_id'), nullable=False),
        sa.Column('investor_id', sa.Integer(), sa.ForeignKey('investors.investor_id'), nullable=False),
        sa.Column('amount_invested', sa.Numeric(15, 2), nullable=True),
        sa.Column('shares', sa.Integer(), nullable=True),
        sa.Column('date_invested', sa.Date(), nullable=True)
    )
    
    # 3. Copy data (ignoring ID to let it auto-increment, or generating it)
    op.execute('INSERT INTO round_investors (round_id, investor_id, amount_invested, date_invested) SELECT round_id, investor_id, amount_invested, date_invested FROM round_investors_old')
    
    # 4. Drop old table
    op.drop_table('round_investors_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_investors', schema=None) as batch_op:
        batch_op.drop_column('id')

    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###
