"""Add acceptance fields to contracts

Revision ID: 5b4f22fd40a1
Revises: fb0b4eeb1bce
Create Date: 2025-12-01 17:04:08.961962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4f22fd40a1'
down_revision = 'fb0b4eeb1bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('founder_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_accepted', sa.Boolean(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('DRAFT', 'SENT', 'SIGNED', 'ACCEPTED', name='contractstatus'),
               existing_nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'FINALIZE_SUBMISSION', 'PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='submissionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'FINALIZE_SUBMISSION', 'PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', name='submissionstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'SIGNED', 'ACCEPTED', name='contractstatus'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.drop_column('admin_accepted')
        batch_op.drop_column('founder_accepted')

    # ### end Alembic commands ###
