"""add created_by to tasks

Revision ID: 6abd74d50466
Revises: ac4b320e04aa
Create Date: 2026-01-26 17:23:19.276170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abd74d50466'
down_revision = 'ac4b320e04aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint to avoid SQLite issues
        batch_op.create_foreign_key('fk_tasks_created_by_users', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_created_by_users', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('cap_table_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_issued', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('investment_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('business_models', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='businessmodelstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'DRAFT'"))
        batch_op.alter_column('model_type',
               existing_type=sa.Enum('SUBSCRIPTION', 'TRANSACTIONAL', 'SERVICE', 'MARKETPLACE', 'ADVERTISING', 'HYBRID', name='businessmodeltype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'TRANSACTIONAL'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('storage_backend',
               existing_type=sa.Enum('LOCAL', 'S3', 'EXTERNAL', 'INLINE', name='storagebackend'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
