"""add_activity_and_notifications

Revision ID: 727b41394c1c
Revises: cdd3bce45d8a
Create Date: 2025-12-01 04:20:51.695378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727b41394c1c'
down_revision = 'cdd3bce45d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_investors', schema=None) as batch_op:
        batch_op.drop_column('ownership_percent')
        batch_op.drop_column('committed_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committed_on', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('ownership_percent', sa.NUMERIC(precision=5, scale=2), nullable=True))

    op.drop_table('activity_logs')
    op.drop_table('dashboard_notifications')
    # ### end Alembic commands ###
