"""Reset and Add CRM

Revision ID: 7956ce9fc61a
Revises: 
Create Date: 2026-01-20 03:18:54.137188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7956ce9fc61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('focus_sectors', sa.JSON(), nullable=True),
    sa.Column('focus_stages', sa.JSON(), nullable=True),
    sa.Column('min_check_size', sa.Float(), nullable=True),
    sa.Column('max_check_size', sa.Float(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.investor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('user_email_integrations', schema=None) as batch_op:
    #     batch_op.drop_index('ix_user_email_integrations_user_id')

    # op.drop_table('user_email_integrations')
    # op.drop_table('sessions')
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startup_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('global_investor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.Enum('PROSPECT', 'CONTACTED', 'MEETING', 'DUE_DILIGENCE', 'TERM_SHEET', 'COMMITTED', 'PASSED', 'PORTFOLIO', name='investorstage'), nullable=True))
        batch_op.add_column(sa.Column('check_size_interest', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('next_action_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_investors_startup_id', 'startups', ['startup_id'], ['id'])
        batch_op.create_foreign_key('fk_investors_global_investor_id', 'global_investors', ['global_investor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_investors_startup_id', type_='foreignkey')
        batch_op.drop_constraint('fk_investors_global_investor_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('next_action_type')
        batch_op.drop_column('next_action_date')
        batch_op.drop_column('check_size_interest')
        batch_op.drop_column('stage')
        batch_op.drop_column('global_investor_id')
        batch_op.drop_column('startup_id')

    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('user_email_integrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=7), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('imap_host', sa.VARCHAR(length=255), nullable=True),
    sa.Column('imap_port', sa.INTEGER(), nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', sa.TEXT(), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_email_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_user_email_integrations_user_id', ['user_id'], unique=False)

    op.drop_table('interaction_logs')
    op.drop_table('global_investors')
    # ### end Alembic commands ###
