"""Initial migration

Revision ID: 7bc3408e306a
Revises: 
Create Date: 2025-11-29 01:55:31.785088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc3408e306a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('investor_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=128), nullable=True),
    sa.Column('linkedin_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('linkedin_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('startup_name', sa.String(length=200), nullable=True),
    sa.Column('founders_and_inspiration', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('who_experiences_problem', sa.Text(), nullable=True),
    sa.Column('product_service_idea', sa.Text(), nullable=True),
    sa.Column('how_solves_problem', sa.Text(), nullable=True),
    sa.Column('intended_users_customers', sa.Text(), nullable=True),
    sa.Column('main_competitors_alternatives', sa.Text(), nullable=True),
    sa.Column('how_stands_out', sa.Text(), nullable=True),
    sa.Column('startup_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('raw_chat_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_submission')
    )
    op.create_table('evaluation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('file_upload_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('problem_analysis', sa.JSON(), nullable=True),
    sa.Column('solution_analysis', sa.JSON(), nullable=True),
    sa.Column('market_analysis', sa.JSON(), nullable=True),
    sa.Column('growth_analysis', sa.JSON(), nullable=True),
    sa.Column('competitor_analysis', sa.JSON(), nullable=True),
    sa.Column('risks_analysis', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(length=100), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('INACTIVE', 'ACTIVE', 'INCUBATING', 'GRADUATED', 'ARCHIVED', name='startupstatus'), nullable=False),
    sa.Column('overall_progress', sa.Float(), nullable=True),
    sa.Column('current_stage', sa.Enum('EVALUATION', 'SCOPING', 'CONTRACT', 'ADMITTED', 'IDEA', 'MVP', 'GROWTH', name='startupstage'), nullable=False),
    sa.Column('next_milestone', sa.String(length=255), nullable=True),
    sa.Column('recent_activity', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startups_slug'), ['slug'], unique=True)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('PRODUCT', 'BUSINESS', 'FUNDRAISE', 'MARKETING', 'GENERAL', name='scope'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'LINK', 'TEXT', name='artifacttype'), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('linked_to_id', sa.Integer(), nullable=True),
    sa.Column('linked_to_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_monthly_data',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_burn', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_in_bank', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mrr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('churn_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('key_highlights', sa.Text(), nullable=True),
    sa.Column('key_challenges', sa.Text(), nullable=True),
    sa.Column('next_focus', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('business_overview',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('business_model', sa.String(length=255), nullable=True),
    sa.Column('key_partners', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('business_id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SIGNED', name='contractstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('PRODUCT', 'BUSINESS', 'FUNDRAISE', 'MARKETING', 'GENERAL', name='scope'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumption', sa.Text(), nullable=True),
    sa.Column('validation_method', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'COMPLETED', name='experimentstatus'), nullable=False),
    sa.Column('linked_to_id', sa.Integer(), nullable=True),
    sa.Column('linked_to_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('founders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('linkedin_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_rounds',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_raised', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valuation_pre', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valuation_post', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('lead_investor', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pitch_deck_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('fundraise_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('funding_stage', sa.String(length=100), nullable=True),
    sa.Column('amount_raised', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('marketing_overview',
    sa.Column('marketing_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('positioning_statement', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('marketing_id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('CONCEPT', 'DEVELOPMENT', 'BETA', 'LIVE', name='productstage'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('targeted_launch_date', sa.Date(), nullable=True),
    sa.Column('actual_launch_date', sa.Date(), nullable=True),
    sa.Column('customer_segment', sa.Text(), nullable=True),
    sa.Column('unique_value_prop', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('PRODUCT', 'BUSINESS', 'FUNDRAISE', 'MARKETING', 'GENERAL', name='scope'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('linked_to_id', sa.Integer(), nullable=True),
    sa.Column('linked_to_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_signatories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='marketingcampaignstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('content_mode', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('next_funding_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundraise_id', sa.Integer(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('target_valuation', sa.Float(), nullable=True),
    sa.Column('target_close_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fundraise_id'], ['fundraise_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundraise_id')
    )
    op.create_table('product_business_details',
    sa.Column('product_business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_model', sa.String(length=255), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('revenue_streams', sa.Text(), nullable=True),
    sa.Column('distribution_channels', sa.Text(), nullable=True),
    sa.Column('cost_structure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_business_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('product_issues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('product_metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('round_investors',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('amount_invested', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ownership_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('committed_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.investor_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['funding_rounds.round_id'], ),
    sa.PrimaryKeyConstraint('round_id', 'investor_id')
    )
    op.create_table('scope_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['scope_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_content_calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('marketing_content_items',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'PUBLISHED', 'CANCELLED', name='marketingcontentstatus'), nullable=False),
    sa.Column('performance', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['marketing_content_calendar.calendar_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_content_items')
    op.drop_table('marketing_content_calendar')
    op.drop_table('scope_comments')
    op.drop_table('round_investors')
    op.drop_table('product_metrics')
    op.drop_table('product_issues')
    op.drop_table('product_business_details')
    op.drop_table('next_funding_goals')
    op.drop_table('marketing_campaigns')
    op.drop_table('features')
    op.drop_table('contract_signatories')
    op.drop_table('contract_comments')
    op.drop_table('tasks')
    op.drop_table('scope_documents')
    op.drop_table('products')
    op.drop_table('marketing_overview')
    op.drop_table('fundraise_details')
    op.drop_table('funding_rounds')
    op.drop_table('founders')
    op.drop_table('experiments')
    op.drop_table('contracts')
    op.drop_table('business_overview')
    op.drop_table('business_monthly_data')
    op.drop_table('artifacts')
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startups_slug'))

    op.drop_table('startups')
    op.drop_table('evaluations')
    op.drop_table('evaluation_tasks')
    op.drop_table('submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('investors')
    # ### end Alembic commands ###
