"""Add unique constraint to user_id in submissions table

Revision ID: 912cd2897df2
Revises: 0d4cb6536701
Create Date: 2025-11-10 18:19:55.649061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912cd2897df2'
down_revision = '0d4cb6536701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_submission', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_submission', type_='unique')

    # ### end Alembic commands ###
