"""Add container_name to Startup model

Revision ID: 94fc951de216
Revises: 5c97ca55241c
Create Date: 2025-12-04 19:13:42.166977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fc951de216'
down_revision = '5c97ca55241c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_startups_container_name', ['container_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_startups_container_name', type_='unique')
        batch_op.drop_column('container_name')

    # ### end Alembic commands ###
