"""add assigned_to to tasks

Revision ID: ac4b320e04aa
Revises: 427589b4da73
Create Date: 2026-01-26 17:04:59.566895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4b320e04aa'
down_revision = '427589b4da73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint to avoid SQLite issues
        batch_op.create_foreign_key('fk_tasks_assigned_to_users', 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assigned_to_users', type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
