"""Add StartupStatus enum and update Startup model

Revision ID: b464f8e52f6b
Revises: 54f045dc4fd6
Create Date: 2025-11-03 23:45:47.247670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b464f8e52f6b'
down_revision = '54f045dc4fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED', name='startupstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'SCOPE_APPROVED', 'CONTRACT_SIGNED', 'IN_COHORT', 'GRADUATED', 'DROPPED', name='startupstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
