"""Add ContractComment model and relationships

Revision ID: c8de5fbad8ae
Revises: 912cd2897df2
Create Date: 2025-11-11 02:29:28.786662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8de5fbad8ae'
down_revision = '912cd2897df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('document_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'SENT', 'SIGNED', name='contractstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'SIGNED', name='contractstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('document_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('signed_at')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('content')

    op.drop_table('contract_comments')
    # ### end Alembic commands ###
