"""Add Firebase fields to User model

Revision ID: cdd3bce45d8a
Revises: 720595df4498
Create Date: 2025-11-29 05:16:04.672946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd3bce45d8a'
down_revision = '720595df4498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_firebase_uid'), ['firebase_uid'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_firebase_uid'), type_='unique')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
