"""Add chat_progress_step to Submission model

Revision ID: f1e1dd31413d
Revises: 7bc3408e306a
Create Date: 2025-11-29 02:37:19.121550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e1dd31413d'
down_revision = '7bc3408e306a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_progress_step', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('chat_progress_step')

    # ### end Alembic commands ###
