"""add feature status

Revision ID: fb0b4eeb1bce
Revises: 727b41394c1c
Create Date: 2025-12-01 05:14:14.395448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0b4eeb1bce'
down_revision = '727b41394c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='featurestatus'), nullable=False, server_default='PENDING'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
